import 'package:flutter/material.dart';
import 'package:flutter_localization/flutter_localization.dart';
import 'package:habitt/data/app_locale.dart';
import 'package:habitt/pages/home/home_page.dart';
import 'package:habitt/pages/shared%20widgets/expandable_app_bar.dart';
import 'package:habitt/services/provider/color_provider.dart';
import 'package:habitt/services/provider/habit_provider.dart';

import 'package:icons_flutter/icons_flutter.dart';
import 'package:provider/provider.dart';

Icon chosenIcon = const Icon(Icons.book);
Icon theIcon = chosenIcon;

class IconsPage extends StatelessWidget {
  const IconsPage({super.key});

  @override
  Widget build(BuildContext context) {
    List<Icon> icons = const [
      Icon(Icons.add),
      Icon(Icons.fastfood_outlined),
      Icon(Icons.shopping_bag_outlined),
      Icon(Icons.attach_money_rounded),
      Icon(Icons.audiotrack),
      Icon(Icons.delete_rounded),
      Icon(Icons.book),
      Icon(Icons.edit_document),
      Icon(Icons.laptop_mac_rounded),
      Icon(Ionicons.md_shirt),
      Icon(Icons.directions_bike),
      Icon(Icons.directions_car),
      Icon(Icons.camera_alt_rounded),
      Icon(Icons.celebration),
      Icon(Icons.cake_rounded),
      Icon(Icons.call),
      Icon(Icons.checkroom_rounded),
      Icon(MaterialCommunityIcons.puzzle),
      Icon(Icons.clean_hands_rounded),
      Icon(MaterialCommunityIcons.tooth),
      Icon(Icons.coffee_rounded),
      Icon(Icons.science_rounded),
      Icon(Icons.door_front_door_rounded),
      Icon(Icons.sports_esports_rounded),
      Icon(Icons.sports_football_rounded),
      Icon(MaterialIcons.fitness_center),
      Icon(MaterialIcons.directions_walk),
      Icon(Icons.water_drop_rounded),
      Icon(Icons.egg_alt),
      Icon(MaterialIcons.hotel),
      Icon(FontAwesome.shower),
      Icon(FontAwesome.book),
      Icon(Icons.account_balance),
      Icon(Icons.airplane_ticket),
      Icon(Icons.alarm),
      Icon(Icons.anchor),
      Icon(Icons.android),
      Icon(Icons.apartment),
      Icon(Icons.apple),
      Icon(Icons.archive),
      Icon(Icons.arrow_circle_up),
      Icon(Icons.art_track),
      Icon(Icons.assignment),
      Icon(Icons.assistant),
      Icon(Icons.attractions),
      Icon(Icons.auto_awesome),
      Icon(Icons.auto_fix_high),
      Icon(Icons.baby_changing_station),
      Icon(Icons.backpack),
      Icon(Icons.bakery_dining),
      Icon(Icons.balcony),
      Icon(Icons.bathroom),
      Icon(Icons.bedtime),
      Icon(Icons.beenhere),
      Icon(Icons.blender),
      Icon(Icons.block),
      Icon(Icons.book_online),
      Icon(Icons.brightness_high),
      Icon(Icons.brunch_dining),
      Icon(Icons.build),
      Icon(Icons.business),
      Icon(Icons.cabin),
      Icon(Icons.cable),
      Icon(Icons.calendar_today),
      Icon(Icons.camera),
      Icon(Icons.campaign),
      Icon(Icons.carpenter),
      Icon(Icons.castle),
      Icon(Icons.category),
      Icon(Icons.catching_pokemon),
      Icon(Icons.cell_tower),
      Icon(Icons.chair),
      Icon(Icons.charging_station),
      Icon(Icons.check_box),
      Icon(Icons.child_care),
      Icon(Icons.cloud),
      Icon(Icons.code),
      Icon(Icons.computer),
      Icon(Icons.construction),
      Icon(Icons.contact_mail),
      Icon(Icons.contacts),
      Icon(Icons.cottage),
      Icon(Icons.credit_card),
      Icon(Icons.cruelty_free),
      Icon(Icons.dining),
      Icon(Icons.discord),
      Icon(Icons.disc_full),
      Icon(Icons.directions),
      Icon(Icons.dock),
      Icon(Icons.document_scanner),
      Icon(Icons.dry),
      Icon(Icons.earbuds),
      Icon(Icons.eco),
      Icon(Icons.electric_bike),
      Icon(Icons.electric_car),
      Icon(Icons.electrical_services),
      Icon(Icons.email),
      Icon(Icons.energy_savings_leaf),
      Icon(Icons.euro),
      Icon(Icons.event),
      Icon(Icons.family_restroom),
      Icon(Icons.fast_forward),
      Icon(Icons.female),
      Icon(Icons.fire_extinguisher),
      Icon(Icons.fit_screen),
      Icon(Icons.flag),
      Icon(Icons.flash_on),
      Icon(Icons.flight_takeoff),
      Icon(Icons.folder),
      Icon(Icons.food_bank),
      Icon(Icons.gavel),
      Icon(Icons.gesture),
      Icon(Icons.golf_course),
      Icon(Icons.grain),
      Icon(Icons.graphic_eq),
      Icon(Icons.group),
      Icon(Icons.handshake),
      Icon(Icons.headphones),
      Icon(Icons.healing),
      Icon(Icons.heart_broken),
      Icon(Icons.home),
      Icon(Icons.hot_tub),
      Icon(Icons.houseboat),
      Icon(Icons.icecream),
      Icon(Icons.inbox),
      Icon(Icons.inventory),
      Icon(Icons.keyboard),
      Icon(Icons.kitchen),
      Icon(Icons.landscape),
      Icon(Icons.lightbulb),
      Icon(Icons.local_hospital),
      Icon(Icons.ac_unit),
      Icon(Icons.access_time),
      Icon(Icons.ad_units),
      Icon(Icons.add_alert),
      Icon(Icons.airline_seat_flat),
      Icon(Icons.airplanemode_active),
      Icon(Icons.all_inbox),
      Icon(Icons.analytics),
      Icon(Icons.animation),
      Icon(Icons.api),
      Icon(Icons.app_settings_alt),
      Icon(Icons.archive_outlined),
      Icon(Icons.attachment),
      Icon(Icons.audiotrack_outlined),
      Icon(Icons.auto_awesome_mosaic),
      Icon(Icons.auto_awesome_motion),
      Icon(Icons.auto_stories),
      Icon(Icons.av_timer),
      Icon(Icons.backup),
      Icon(Icons.battery_alert),
      Icon(Icons.beach_access),
      Icon(Icons.bedroom_child),
      Icon(Icons.bento),
      Icon(Icons.bike_scooter),
      Icon(Icons.biotech),
      Icon(Icons.bloodtype),
      Icon(Icons.bluetooth_audio),
      Icon(Icons.border_all),
      Icon(Icons.brightness_4),
      Icon(Icons.broken_image),
      Icon(Icons.bubble_chart),
      Icon(Icons.bug_report),
      Icon(Icons.calendar_month),
      Icon(Icons.camera_outdoor),
      Icon(Icons.car_rental),
      Icon(Icons.category_outlined),
      Icon(Icons.center_focus_strong),
      Icon(Icons.checklist),
      Icon(Icons.child_friendly),
      Icon(Icons.cleaning_services),
      Icon(Icons.cloud_circle),
      Icon(Icons.color_lens),
      Icon(Icons.compare),
      Icon(Icons.connected_tv),
      Icon(Icons.contact_support),
      Icon(Icons.content_paste),
      Icon(Icons.create_new_folder),
      Icon(Icons.crib),
      Icon(Icons.currency_exchange),
      Icon(Icons.dashboard_customize),
      Icon(Icons.data_object),
      Icon(Icons.dataset),
      Icon(Icons.developer_mode),
      Icon(Icons.directions_boat),
      Icon(Icons.discount),
      Icon(Icons.domain),
      Icon(Icons.download_done),
      Icon(Icons.dvr),
      Icon(Icons.electric_rickshaw),
      Icon(Icons.elderly),
      Icon(Icons.email_outlined),
      Icon(Icons.emoji_flags),
      Icon(Icons.escalator),
      Icon(Icons.event_repeat),
      Icon(Icons.expand_less),
      Icon(Icons.explicit),
      Icon(Icons.explore),
      Icon(Icons.face_unlock_rounded),
      Icon(Icons.factory),
      Icon(Icons.fence),
      Icon(Icons.filter_alt),
      Icon(Icons.fire_hydrant),
      Icon(Icons.fireplace),
      Icon(Icons.flight_land),
      Icon(Icons.flood),
      Icon(Icons.folder_special),
      Icon(Icons.forest),
      Icon(Icons.format_color_fill),
      Icon(Icons.format_quote),
      Icon(Icons.foundation),

      Icon(Icons.girl),
      Icon(Icons.grade),
      Icon(Icons.grid_4x4),
      Icon(Icons.hail),
      Icon(Icons.holiday_village),
      Icon(Icons.home_max),
      Icon(Icons.hourglass_bottom),
      Icon(Icons.ice_skating),
      Icon(Icons.import_contacts),
      Icon(Icons.integration_instructions),
      Icon(Icons.inventory_2),
      Icon(Icons.keyboard_arrow_down),
      Icon(Icons.kitesurfing),
      Icon(Icons.library_music),
      Icon(Icons.liquor),
      Icon(Icons.local_bar),
      Icon(Icons.lock_clock),
      Icon(Icons.masks),
      Icon(Icons.medication),
      Icon(Icons.menu_open),
      Icon(Icons.microwave),
      Icon(Icons.military_tech),
      Icon(Icons.mode_comment),
      Icon(Icons.money_off),
      Icon(Icons.moving),
      Icon(Icons.movie_filter),
      Icon(Icons.multiline_chart),
      Icon(Icons.nature_people),
      Icon(Icons.night_shelter),
      Icon(Icons.nights_stay),
      Icon(Icons.no_cell),
      Icon(Icons.no_drinks),
      Icon(Icons.ondemand_video),
      Icon(Icons.online_prediction),
      Icon(Icons.open_in_full),
      Icon(Icons.outdoor_grill),
      Icon(Icons.pages),
      Icon(Icons.panorama),
      Icon(Icons.paragliding),
      Icon(Icons.party_mode),
      Icon(Icons.password),
      Icon(Icons.pedal_bike),
      Icon(Icons.perm_identity),
      Icon(Icons.pets),
      Icon(Icons.phonelink_erase),
      Icon(Icons.photo_camera_back),
      Icon(Icons.photo_filter),
      Icon(Icons.place),
      Icon(Icons.plumbing),
      Icon(Icons.pool),
      Icon(Icons.pregnant_woman),
      Icon(Icons.privacy_tip),
      Icon(Icons.psychology),
      Icon(Icons.publish),
      Icon(Icons.quiz),
      Icon(Icons.ramen_dining),
      Icon(Icons.rate_review),
      Icon(Icons.recycling),
      Icon(Icons.remove_from_queue),
      Icon(Icons.rice_bowl),
      Icon(Icons.rocket),
      Icon(Icons.roofing),
      Icon(Icons.rotate_left),
      Icon(Icons.rowing),
      Icon(Icons.rule),
      Icon(Icons.run_circle),
      Icon(Icons.rv_hookup),
      Icon(Icons.sanitizer),
      Icon(Icons.save_alt),
      Icon(Icons.school),
      Icon(Icons.scuba_diving),
      Icon(Icons.search_off),
      Icon(Icons.security_update),
      Icon(Icons.sensors),
      Icon(Icons.sentiment_very_dissatisfied),
      Icon(Icons.severe_cold),
      Icon(Icons.shield),
      Icon(Icons.shortcut),
      Icon(Icons.shopping_basket),
      Icon(Icons.signal_wifi_off),
      Icon(Icons.sim_card_alert),
      Icon(Icons.skateboarding),
      Icon(Icons.sledding),
      Icon(Icons.slow_motion_video),
      Icon(Icons.smart_button),
      Icon(Icons.sports_basketball),
      Icon(Icons.sports_cricket),
      Icon(Icons.sports_hockey),
      Icon(Icons.stacked_bar_chart),
      Icon(Icons.star_half),
      Icon(Icons.surfing),
      Icon(Icons.switch_account),
      Icon(Icons.sync_alt),
      Icon(Icons.system_update_alt),
      Icon(Icons.table_chart),
      Icon(Icons.terrain),
      Icon(Icons.theater_comedy),
      Icon(Icons.timer_off),
      Icon(Icons.token),
      Icon(Icons.trending_down),
      Icon(Icons.trolley),
      Icon(Icons.turn_slight_left),
      Icon(Icons.tv_off),
      Icon(Icons.unfold_less),
      Icon(Icons.video_label),
      Icon(Icons.volunteer_activism),
      Icon(Icons.wash),
      Icon(Icons.waves),
      Icon(Icons.wheelchair_pickup),
      Icon(Icons.work_history),
      Icon(Icons.zoom_out_map),
      Icon(Ionicons.md_alarm),
      Icon(FontAwesome5.address_card),
      Icon(FontAwesome.glass),
      Icon(MaterialCommunityIcons.apple_finder),
      Icon(Icons.directions_run), // Running icon
      Icon(Icons.sports_handball), // Handball icon
      Icon(Icons.sports_gymnastics), // Gymnastics icon
      Icon(Icons.sports_mma), // Martial arts icon
      Icon(Icons.sports_volleyball), // Volleyball icon
      Icon(Icons.sports_tennis), // Tennis icon
      Icon(Icons.sports_football), // Football icon
      Icon(Icons.sports_basketball), // Basketball icon
      Icon(Icons.self_improvement), // Yoga/meditation
      Icon(Icons.cyclone), // Cycling workout
      Icon(Icons.snowboarding), // Snowboarding
      Icon(Icons.hiking), // Hiking
      Icon(Ionicons.md_walk), // Walking
      Icon(MaterialCommunityIcons.run_fast), // Fast running
    ];

    return Scaffold(
      backgroundColor: context.watch<ColorProvider>().blackColor,
      body: CustomScrollView(
        physics: const BouncingScrollPhysics(),
        slivers: [
          ExpandableAppBar(
            actionsWidget: const SizedBox(),
            title: AppLocale.chooseAnIcon.getString(context),
          ),
          SliverPadding(
            padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 15),
            sliver: SliverGrid(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  final icon = icons[index];
                  return IconWidget(icon: icon);
                },
                childCount: icons.length,
              ),
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: _getCrossAxisCount(context),
                crossAxisSpacing: 15,
                mainAxisSpacing: 15,
              ),
            ),
          ),
        ],
      ),
    );
  }

  int _getCrossAxisCount(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    print("screen width: $screenWidth");
    if (screenWidth < 200) return 2;
    if (screenWidth < 400) return 3;
    if (screenWidth < 600) return 4;
    if (screenWidth < 800) return 5;
    return 6;
  }
}

class IconWidget extends StatelessWidget {
  final Icon icon;

  const IconWidget({
    super.key,
    required this.icon,
  });

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: 1,
      child: SizedBox(
        child: ElevatedButton(
          onPressed: () {
            Provider.of<HabitProvider>(context, listen: false).updatedIcon =
                icon;
            Navigator.pop(context);
            changed = true;
            Provider.of<HabitProvider>(context, listen: false)
                .updateAppearenceEdited();
            Provider.of<HabitProvider>(context, listen: false)
                .updateSomethingEdited();
          },
          style: ElevatedButton.styleFrom(
            padding: const EdgeInsets.all(0),
            backgroundColor: context.watch<ColorProvider>().greyColor,
            elevation: 0,
            shape: const RoundedRectangleBorder(
              borderRadius: BorderRadius.all(Radius.circular(15)),
            ),
          ),
          child: Icon(
            icon.icon,
            color: Colors.white,
            size: 30,
          ),
        ),
      ),
    );
  }
}
