// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYKhcU9-RtFY5jatuO5v4Sg2_eyHibDQ',
    appId: '1:752709751941:web:6d71b0b71d97c2b60005ec',
    messagingSenderId: '752709751941',
    projectId: 'habit-tracker-df84b',
    authDomain: 'habit-tracker-df84b.firebaseapp.com',
    storageBucket: 'habit-tracker-df84b.appspot.com',
    measurementId: 'G-GB43QTZZNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDArWvksa_cBebWkn4H7VF1C7-sgEgPtq0',
    appId: '1:752709751941:android:d45e25110a0f29100005ec',
    messagingSenderId: '752709751941',
    projectId: 'habit-tracker-df84b',
    storageBucket: 'habit-tracker-df84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnBWaRfW_fxzNKLqHO3x_gXe0bBIPcmU',
    appId: '1:752709751941:ios:c690bfa1f3872c530005ec',
    messagingSenderId: '752709751941',
    projectId: 'habit-tracker-df84b',
    storageBucket: 'habit-tracker-df84b.appspot.com',
    androidClientId: '752709751941-rp25a50jrijcslhc9fl2qv9c2dthla3n.apps.googleusercontent.com',
    iosClientId: '752709751941-8ejpmuhbq5d05kc7d538hji7fe2pm3o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnBWaRfW_fxzNKLqHO3x_gXe0bBIPcmU',
    appId: '1:752709751941:ios:c690bfa1f3872c530005ec',
    messagingSenderId: '752709751941',
    projectId: 'habit-tracker-df84b',
    storageBucket: 'habit-tracker-df84b.appspot.com',
    androidClientId: '752709751941-rp25a50jrijcslhc9fl2qv9c2dthla3n.apps.googleusercontent.com',
    iosClientId: '752709751941-8ejpmuhbq5d05kc7d538hji7fe2pm3o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYKhcU9-RtFY5jatuO5v4Sg2_eyHibDQ',
    appId: '1:752709751941:web:cc3483c1c2f033320005ec',
    messagingSenderId: '752709751941',
    projectId: 'habit-tracker-df84b',
    authDomain: 'habit-tracker-df84b.firebaseapp.com',
    storageBucket: 'habit-tracker-df84b.appspot.com',
    measurementId: 'G-PT4GLRDPL8',
  );

}